sudo: required

services:
  - docker

before_install:
  - gem install bundler:2.2.33
  - docker-compose up --build -d

script:
  - docker-compose exec web rails db:create RAILS_ENV=test
  - docker-compose exec web rails db:migrate RAILS_ENV=test
  - docker-compose exec web rails test
